export const servicesData = [
  {
    slug: 'web-application-vapt',
    title: 'Web Application VAPT',
    shortTitle: 'Web App VAPT',
    metaTitle: 'Web Application VAPT India | OWASP Testing | BugZero Cyber Solutions',
    metaDescription: 'Professional web application vulnerability assessment and penetration testing (VAPT) in India. OWASP Top 10, business logic testing, SQL injection, XSS & more. Starting ₹25,000.',
    keywords: 'web application VAPT India, website security testing, OWASP Top 10 testing, web penetration testing India, web app security audit',
    category: 'VAPT',
    price: '25000',
    priceDisplay: '₹25,000',
    icon: 'Globe',
    badge: 'Most Popular',
    summary: 'Comprehensive vulnerability assessment and penetration testing for web applications. We cover OWASP Top 10, business logic flaws, authentication bypass, and deliver detailed remediation reports.',
    description: `Web Application VAPT (Vulnerability Assessment and Penetration Testing) is a systematic security testing approach to identify, classify, and remediate security vulnerabilities in your web applications before attackers can exploit them.

Our certified ethical hackers follow industry-standard methodologies including OWASP Testing Guide, PTES, and OWASP Top 10 to provide the most comprehensive coverage for your web application security.`,
    whatWeTest: [
      'Authentication & Session Management flaws',
      'SQL Injection and NoSQL Injection',
      'Cross-Site Scripting (XSS) — Stored, Reflected, DOM-based',
      'Cross-Site Request Forgery (CSRF)',
      'Insecure Direct Object Reference (IDOR)',
      'Business Logic Vulnerabilities',
      'XML External Entity (XXE) Injection',
      'Server-Side Request Forgery (SSRF)',
      'Security Misconfigurations',
      'Sensitive Data Exposure',
      'Broken Access Control',
      'Security Headers & HTTPS/TLS configuration',
    ],
    deliverables: [
      'Executive Summary Report (for management)',
      'Technical Report with CVSS scoring',
      'Proof of Concept for each vulnerability',
      'Risk-prioritized remediation roadmap',
      'Compliance mapping (ISO 27001, PCI DSS)',
      'Re-testing after fixes (1 round included)',
    ],
    faq: [
      { question: 'How long does a web application VAPT take?', answer: 'A standard web application VAPT takes 3-7 business days depending on the application size and complexity. Large enterprise applications may take up to 14 days.' },
      { question: 'What is the difference between VAPT and a vulnerability scan?', answer: 'A vulnerability scan is automated and only identifies known vulnerabilities. VAPT includes manual testing, business logic testing, and actual exploitation attempts to validate the real risk.' },
      { question: 'Will VAPT testing affect my live website?', answer: 'We conduct testing in a controlled manner to avoid service disruption. We recommend testing on a staging environment, but we can test production with agreed time windows.' },
    ],
  },
  {
    slug: 'penetration-testing',
    title: 'Penetration Testing',
    shortTitle: 'Pen Testing',
    metaTitle: 'Penetration Testing Services India | Red Team | BugZero Cyber Solutions',
    metaDescription: 'Advanced manual penetration testing services in India. Red team exercises, social engineering, full-scope network & application pen testing. OSCP-certified ethical hackers. Starting ₹45,000.',
    keywords: 'penetration testing India, ethical hacking services India, red team testing India, pen testing services, OSCP certified hackers India',
    category: 'Penetration Testing',
    price: '45000',
    priceDisplay: '₹45,000',
    icon: 'Shield',
    badge: 'Advanced',
    summary: 'Advanced manual penetration testing simulating real-world cyberattacks. Red team exercises, social engineering, and full-scope assessments by OSCP-certified security professionals.',
    description: `Penetration testing goes beyond automated scanning to simulate real-world attacks by skilled adversaries. Our OSCP-certified ethical hackers use advanced techniques including custom exploits, lateral movement, and privilege escalation to identify the true security posture of your organization.

Our penetration testing methodology follows PTES (Penetration Testing Execution Standard) and NIST guidelines, ensuring comprehensive coverage across all attack surfaces.`,
    whatWeTest: [
      'External Network Penetration Testing',
      'Internal Network Penetration Testing',
      'Web & Mobile Application Penetration Testing',
      'Social Engineering (Phishing, Vishing)',
      'Physical Security Assessment',
      'Active Directory / LDAP attacks',
      'Lateral Movement & Privilege Escalation',
      'Custom Exploit Development',
      'Post-Exploitation & Data Exfiltration Simulation',
      'Wireless Network Penetration Testing',
    ],
    deliverables: [
      'Executive Board-Level Report',
      'Detailed Technical Findings Report',
      'Attack Chain Diagrams',
      'MITRE ATT&CK Framework Mapping',
      'Risk-Based Remediation Roadmap',
      'Re-test Certificate upon fix verification',
    ],
    faq: [
      { question: 'What is the difference between penetration testing and VAPT?', answer: 'VAPT focuses on identifying and validating vulnerabilities. Penetration testing goes further — simulating full attack chains, lateral movement, and adversary tactics to assess the real-world impact.' },
      { question: 'Do you offer red team vs. blue team exercises?', answer: 'Yes, we offer full red team exercises where our team simulates advanced persistent threats (APTs) while your internal security team (blue team) attempts to detect and respond.' },
    ],
  },
  {
    slug: 'api-security-testing',
    title: 'API Security Testing',
    shortTitle: 'API Security',
    metaTitle: 'API Security Testing India | REST & GraphQL VAPT | BugZero',
    metaDescription: 'Comprehensive API security testing for REST, GraphQL, and SOAP APIs in India. OWASP API Top 10 coverage, authentication bypass, IDOR, mass assignment vulnerabilities. Starting ₹20,000.',
    keywords: 'API security testing India, REST API penetration testing, GraphQL security audit, API VAPT India, API vulnerability assessment',
    category: 'API Security',
    price: '20000',
    priceDisplay: '₹20,000',
    icon: 'Code',
    badge: null,
    summary: 'In-depth security testing of REST, GraphQL, and SOAP APIs covering OWASP API Top 10, authentication flaws, IDOR, mass assignment, and data exposure vulnerabilities.',
    description: `APIs are the backbone of modern applications and a prime target for attackers. Our API security testing service covers all OWASP API Security Top 10 vulnerabilities and beyond, providing comprehensive protection for your API infrastructure.`,
    whatWeTest: [
      'Broken Object Level Authorization (IDOR)',
      'Broken Authentication & JWT flaws',
      'Excessive Data Exposure',
      'Lack of Resource Rate Limiting',
      'Broken Function Level Authorization',
      'Mass Assignment vulnerabilities',
      'Security Misconfiguration',
      'Injection (SQL, NoSQL, Command)',
      'GraphQL-specific attacks (introspection, batching)',
      'API versioning and deprecation issues',
    ],
    deliverables: [
      'OWASP API Top 10 Coverage Report',
      'Postman collection with attack payloads',
      'Technical findings with CVSS scores',
      'Developer-friendly remediation guide',
      'Re-testing included',
    ],
    faq: [
      { question: 'What API types do you test?', answer: 'We test REST, GraphQL, SOAP, WebSocket, and gRPC APIs. We also test API gateways and microservices architectures.' },
      { question: 'Do you need API documentation for testing?', answer: 'Documentation (Swagger/OpenAPI spec) is helpful but not required. Our team can perform black-box API discovery and testing without prior documentation.' },
    ],
  },
  {
    slug: 'network-security',
    title: 'Network Security Assessment',
    shortTitle: 'Network Security',
    metaTitle: 'Network Security Assessment India | Infrastructure VAPT | BugZero',
    metaDescription: 'Complete network security assessment and penetration testing in India. Internal & external network testing, firewall audit, VLAN review, wireless security. Starting ₹35,000.',
    keywords: 'network security assessment India, network penetration testing India, infrastructure security audit, firewall security audit India, network VAPT',
    category: 'Network Security',
    price: '35000',
    priceDisplay: '₹35,000',
    icon: 'Server',
    badge: 'Government Grade',
    summary: 'Complete network infrastructure security assessment including internal/external penetration testing, firewall configuration review, segmentation analysis, and wireless security testing.',
    description: `Network security assessment is critical for identifying weaknesses in your infrastructure before adversaries exploit them. Our team performs both external and internal network penetration testing following NIST and PTES standards.`,
    whatWeTest: [
      'External Network Penetration Testing',
      'Internal Network Segmentation Testing',
      'Firewall Rules & ACL Review',
      'VLAN Segmentation Analysis',
      'Active Directory Security Assessment',
      'DNS Security Review',
      'Router & Switch Configuration Audit',
      'VPN Security Assessment',
      'Wireless Network Security (WPA2/WPA3)',
      'Network Device Hardening Review',
    ],
    deliverables: [
      'Network Topology Security Map',
      'Vulnerability Risk Matrix',
      'Firewall Policy Recommendations',
      'Network Hardening Checklist',
      'Compliance Report (ISO 27001, PCI DSS)',
      'Executive Summary',
    ],
    faq: [
      { question: 'Do you test both internal and external networks?', answer: 'Yes, we perform both external (internet-facing) and internal network assessments. Internal testing requires VPN access or on-site presence.' },
      { question: 'Can you test government networks?', answer: 'Yes, we have experience working with government organizations and follow NIC guidelines for government network security assessments.' },
    ],
  },
  {
    slug: 'cloud-security-audit',
    title: 'Cloud Security Audit',
    shortTitle: 'Cloud Security',
    metaTitle: 'Cloud Security Audit India | AWS Azure GCP VAPT | BugZero',
    metaDescription: 'Expert cloud security audit for AWS, Azure, and Google Cloud in India. IAM review, S3 bucket misconfiguration, compliance mapping, and cloud penetration testing. Starting ₹40,000.',
    keywords: 'cloud security audit India, AWS security assessment India, Azure security review India, GCP security audit, cloud VAPT India, cloud security services India',
    category: 'Cloud Security',
    price: '40000',
    priceDisplay: '₹40,000',
    icon: 'Cloud',
    badge: 'Enterprise',
    summary: 'Comprehensive cloud infrastructure security audit for AWS, Azure, and GCP. Covers IAM misconfigurations, exposed storage, insecure services, and compliance requirements.',
    description: `As organizations migrate to the cloud, misconfigured cloud services have become the #1 cause of data breaches. Our cloud security audit service identifies misconfigurations, insecure access controls, and compliance gaps across your cloud infrastructure.`,
    whatWeTest: [
      'IAM Policies & Role Permissions Audit',
      'S3 Bucket / Blob Storage Public Exposure',
      'Security Group & Network ACL Review',
      'Lambda / Cloud Function Security',
      'Container & Kubernetes Security',
      'Cloud Database Exposure (RDS, DynamoDB)',
      'Secret Management & Rotation',
      'CloudTrail / Azure Monitor Logging Review',
      'Multi-Factor Authentication Enforcement',
      'Compliance Mapping (CIS, ISO 27001, PCI DSS)',
    ],
    deliverables: [
      'Cloud Security Posture Report',
      'CIS Benchmark Assessment',
      'IAM Remediation Plan',
      'Infrastructure-as-Code (IaC) Security Review',
      'Compliance Gap Analysis',
      'Priority-based Risk Remediation Guide',
    ],
    faq: [
      { question: 'Which cloud platforms do you support?', answer: 'We support AWS, Microsoft Azure, Google Cloud Platform (GCP), Oracle Cloud, and hybrid/multi-cloud environments.' },
      { question: 'Do we need to give you admin access?', answer: 'We work with read-only or security-audit roles. We follow the principle of least privilege and document all access provided during the engagement.' },
    ],
  },
  {
    slug: 'mobile-app-security',
    title: 'Mobile App Security Testing',
    shortTitle: 'Mobile Security',
    metaTitle: 'Mobile App Security Testing India | Android iOS VAPT | BugZero',
    metaDescription: 'Expert mobile application security testing for Android and iOS apps in India. OWASP Mobile Top 10, static/dynamic analysis, backend API testing. Starting ₹30,000.',
    keywords: 'mobile app security testing India, Android security testing India, iOS app VAPT, mobile app penetration testing, OWASP Mobile Top 10 testing',
    category: 'Mobile Security',
    price: '30000',
    priceDisplay: '₹30,000',
    icon: 'Smartphone',
    badge: null,
    summary: 'Comprehensive security testing for Android and iOS mobile applications. Covers OWASP Mobile Top 10, static & dynamic analysis, data storage security, and backend API testing.',
    description: `Mobile applications handle sensitive user data and business-critical operations, making them a prime target for attackers. Our mobile application security testing follows OWASP Mobile Top 10 and MASTG guidelines to identify vulnerabilities in the app binary, runtime behavior, and backend APIs.`,
    whatWeTest: [
      'Static Analysis (SAST) — APK/IPA reverse engineering',
      'Dynamic Analysis (DAST) — Runtime behavior analysis',
      'Data Storage Security (SQLite, SharedPreferences, Keychain)',
      'Insecure Communication (SSL/TLS pinning bypass)',
      'Authentication & Session Management',
      'Backend API Security Testing',
      'Insecure Third-Party Libraries',
      'Clipboard & Screenshot vulnerabilities',
      'Jailbreak / Root Detection bypass',
      'Code Obfuscation Assessment',
    ],
    deliverables: [
      'OWASP Mobile Top 10 Coverage Report',
      'MASTG Compliance Assessment',
      'Static & Dynamic Analysis Findings',
      'Backend API Security Report',
      'Developer Remediation Guide',
      'Re-testing included',
    ],
    faq: [
      { question: 'Do you test both Android and iOS apps?', answer: 'Yes, we test both Android (APK) and iOS (IPA) applications. We use industry-standard tools like MobSF, Frida, Burp Suite, and custom scripts.' },
    ],
  },
  {
    slug: 'bug-bounty-management',
    title: 'Bug Bounty Program Management',
    shortTitle: 'Bug Bounty',
    metaTitle: 'Bug Bounty Program Management India | VDP Setup | BugZero',
    metaDescription: 'Professional bug bounty program design, launch, and management for Indian enterprises. Vulnerability disclosure policy, researcher triage, reward management, and monthly reporting.',
    keywords: 'bug bounty program India, vulnerability disclosure program India, bug bounty management service, VDP setup India, security researcher program India',
    category: 'Bug Bounty',
    price: null,
    priceDisplay: 'Custom',
    icon: 'Bug',
    badge: null,
    summary: 'End-to-end bug bounty program design, launch, and management. We handle researcher triage, vulnerability validation, reward management, and provide monthly executive reports.',
    description: `Bug bounty programs enable organizations to harness the power of the global security research community to identify vulnerabilities. BugZero manages the entire lifecycle — from program design to researcher coordination and vulnerability triage.`,
    whatWeTest: [
      'Bug Bounty Program Strategy & Design',
      'Scope Definition & Policy Documentation',
      'Researcher Onboarding & Communication',
      'Vulnerability Triage & Validation',
      'Duplicate Detection & False Positive filtering',
      'Severity Assessment & CVSS Scoring',
      'Reward Management & Payouts',
      'Monthly Security Intelligence Reports',
      'Responsible Disclosure Policy (RDP) setup',
      'Integration with existing security workflows',
    ],
    deliverables: [
      'Bug Bounty Program Handbook',
      'Vulnerability Disclosure Policy',
      'Monthly Activity & Security Reports',
      'Researcher Leaderboard',
      'Trend Analysis & Risk Dashboard',
    ],
    faq: [
      { question: 'What is the difference between a bug bounty program and a VDP?', answer: 'A VDP (Vulnerability Disclosure Program) is free — researchers report bugs without monetary rewards. A Bug Bounty Program pays researchers for valid findings. Both are managed by BugZero.' },
    ],
  },
  {
    slug: 'security-code-review',
    title: 'Security Code Review',
    shortTitle: 'Code Review',
    metaTitle: 'Security Code Review Service India | SAST | BugZero Cyber',
    metaDescription: 'Manual and automated security code review for web, mobile, and backend applications in India. SAST integration, secure coding guidelines, and CI/CD pipeline security.',
    keywords: 'security code review India, SAST India, secure code review service, source code security audit India, application security review India',
    category: 'Application Security',
    price: null,
    priceDisplay: 'Custom',
    icon: 'Code',
    badge: null,
    summary: 'Manual and automated source code security review to identify vulnerabilities in your codebase before deployment. Covers SAST, insecure patterns, and CI/CD pipeline security.',
    description: `Security code review identifies vulnerabilities at the source — before code reaches production. Combining manual expert review with automated SAST tools, we provide comprehensive coverage across all major programming languages and frameworks.`,
    whatWeTest: [
      'Manual Source Code Review (critical paths)',
      'SAST Tool Integration (SonarQube, Semgrep, CodeQL)',
      'Injection Vulnerabilities in code',
      'Cryptographic Implementation Review',
      'Authentication & Authorization logic',
      'Insecure Deserialization patterns',
      'Hardcoded Secrets & API Keys',
      'Third-party dependency vulnerabilities',
      'CI/CD Pipeline Security Review',
      'Secure Coding Standard compliance',
    ],
    deliverables: [
      'Code Review Findings Report',
      'Secure Coding Guidelines Document',
      'SAST Tool Configuration',
      'CI/CD Integration Recommendations',
      'Developer Security Training (optional)',
    ],
    faq: [
      { question: 'Which programming languages do you support?', answer: 'We support JavaScript/TypeScript, Python, Java, Go, PHP, Ruby, C/C++, C#, and more. Our team has expertise across major web frameworks and mobile platforms.' },
    ],
  },
  {
    slug: 'database-security',
    title: 'Database Security Assessment',
    shortTitle: 'Database Security',
    metaTitle: 'Database Security Assessment India | MySQL Oracle MongoDB | BugZero',
    metaDescription: 'Comprehensive database security audit for MySQL, PostgreSQL, MongoDB, Oracle, and SQL Server. Access control review, encryption audit, and compliance checks. India.',
    keywords: 'database security audit India, MySQL security assessment, MongoDB security testing, database VAPT India, SQL server security review',
    category: 'Database Security',
    price: null,
    priceDisplay: 'Custom',
    icon: 'Database',
    badge: 'Government Grade',
    summary: 'Comprehensive database security audit covering access controls, encryption, configuration hardening, SQL injection risk, and data protection compliance.',
    description: `Databases store your most sensitive assets. Our database security assessment identifies misconfigurations, weak access controls, unencrypted sensitive data, and compliance gaps across all major database platforms.`,
    whatWeTest: [
      'User Privilege & Access Control Audit',
      'Authentication Configuration Review',
      'Encryption at Rest & In Transit',
      'SQL Injection Risk Assessment',
      'Database Activity Monitoring',
      'Backup & Recovery Security',
      'Stored Procedures & Triggers Review',
      'Default Credentials & Patch Status',
      'Audit Logging Configuration',
      'PII Data Discovery & Classification',
    ],
    deliverables: [
      'Database Security Posture Report',
      'Access Control Remediation Plan',
      'Encryption Implementation Guide',
      'Compliance Report (PCI DSS, HIPAA, ISO 27001)',
    ],
    faq: [
      { question: 'Which databases do you support?', answer: 'We support MySQL, PostgreSQL, MongoDB, Oracle, Microsoft SQL Server, Redis, Cassandra, and cloud-managed databases (RDS, Aurora, CosmosDB).' },
    ],
  },
  {
    slug: 'compliance-consulting',
    title: 'Security Consulting & Compliance',
    shortTitle: 'Compliance',
    metaTitle: 'ISO 27001 Compliance Consulting India | PCI DSS SOC 2 | BugZero',
    metaDescription: 'Expert ISO 27001, SOC 2, PCI DSS, GDPR, and HIPAA compliance consulting in India. Gap analysis, policy development, and certification support. Trusted by enterprises & government.',
    keywords: 'ISO 27001 compliance India, PCI DSS consulting India, SOC 2 readiness India, GDPR compliance India, cybersecurity compliance consulting India',
    category: 'Compliance',
    price: null,
    priceDisplay: 'Custom',
    icon: 'Shield',
    badge: null,
    summary: 'Expert consulting for ISO 27001, SOC 2, PCI DSS, HIPAA, and GDPR compliance. Gap analysis, policy development, ISMS implementation, and certification support.',
    description: `Compliance with information security standards is increasingly mandatory for enterprises and government organizations. Our consulting team guides you through the complete compliance journey — from gap analysis to certification.`,
    whatWeTest: [
      'ISO 27001 Gap Analysis & ISMS Implementation',
      'SOC 2 Type I & Type II Readiness',
      'PCI DSS Level 1-4 Compliance',
      'GDPR Data Protection Assessment',
      'HIPAA Security Rule Compliance',
      'RBI Cybersecurity Framework (India)',
      'CERT-In Guidelines Compliance',
      'Security Policy & Procedure Development',
      'Risk Assessment & Risk Treatment Plan',
      'Security Awareness Training Program',
    ],
    deliverables: [
      'Compliance Gap Analysis Report',
      'Risk Assessment Report',
      'Information Security Policy Suite',
      'ISMS Documentation Set',
      'Audit Readiness Checklist',
      'Remediation Roadmap with timelines',
    ],
    faq: [
      { question: 'How long does ISO 27001 certification take?', answer: 'ISO 27001 certification typically takes 6-12 months depending on organization size and existing security maturity. BugZero accelerates this with pre-built documentation templates and expert guidance.' },
      { question: 'Do you help with CERT-In compliance?', answer: 'Yes, we help organizations comply with CERT-In (Computer Emergency Response Team India) guidelines including the mandatory 6-hour reporting requirement.' },
    ],
  },
];

export function getServiceBySlug(slug) {
  return servicesData.find((s) => s.slug === slug) || null;
}

export function getAllServiceSlugs() {
  return servicesData.map((s) => s.slug);
}
